[package]
name = "evestaticdata"
version = "0.1.0"
edition = "2024"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json", "indexmap/serde"]

[dependencies]
indexmap = { version = "2.8.0" }
serde = { version = "1.0.219", features = ["derive"], optional = true }
serde_json = { version = "1.0.140", optional = true }